---
title: ACMSA
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
theme: jekyll-theme-cayman
remote_theme: mmistakes/so-simple-theme
